// src/world/wilderness.js — a catalog of 150 unique wilderness encounters that
// fill the empty stretches between regions, so travel always has something to
// find, fight, forage, or read. placeWilderness() (map.js) scatters instances of
// these into the gaps at ~22-tile spacing, matched to the local biome + tier.
//
// Fields: id, name, kind, tier, biome, color, blurb, [loot], [base], [n]
//   kind  : fight (spawns mobs) | explore | gather | treasure | lore | oddity | shrine
//   tier  : low (~lvl 1-20) | mid (20-45) | high (45+) | any
//   biome : any | grass | forest | rock | water | swamp | sand
//   loot  : item id granted once on examine (guarded — skipped if the id is unknown)
//   base  : ENEMY_TYPES key to spawn (fight only); n = how many

export const WILDERNESS = [
  // --- Ruins & old structures (explore/lore) -------------------------------
  { id: 'collapsed_watchtower', name: 'Collapsed Watchtower', kind: 'explore', tier: 'low', biome: 'grass', color: 0x8a8a7a, blurb: 'Toppled stones, home now to spiders.', loot: 'copper_ore' },
  { id: 'sunken_shrine', name: 'Sunken Shrine', kind: 'explore', tier: 'mid', biome: 'water', color: 0x7a8a9a, blurb: 'A shrine half-drowned in the shallows.' },
  { id: 'broken_obelisk', name: 'Broken Obelisk', kind: 'lore', tier: 'mid', biome: 'grass', color: 0x9a9aa0, blurb: "Cracked runes you can't quite read." },
  { id: 'old_well', name: 'Old Well', kind: 'explore', tier: 'low', biome: 'grass', color: 0x6a6a6a, blurb: 'A dry well. Something glints below.', loot: 'coins' },
  { id: 'hollow_stump', name: 'Hollow Stump Hideout', kind: 'explore', tier: 'low', biome: 'forest', color: 0x5a4530, blurb: 'A hollowed trunk someone once slept in.' },
  { id: 'forgotten_milestone', name: 'Forgotten Milestone', kind: 'lore', tier: 'low', biome: 'any', color: 0x8a8a7a, blurb: 'A worn milestone to a town long gone.' },
  { id: 'cracked_sarcophagus', name: 'Cracked Sarcophagus', kind: 'explore', tier: 'mid', biome: 'grass', color: 0x7a7a7a, blurb: 'The lid has slipped. Dare you look?', loot: 'coins' },
  { id: 'toppled_idol', name: 'Toppled Idol', kind: 'explore', tier: 'mid', biome: 'grass', color: 0x8a7a5a, blurb: 'A fallen god, face-down in the grass.' },
  { id: 'mossy_archway', name: 'Mossy Archway', kind: 'explore', tier: 'low', biome: 'forest', color: 0x5a6a4a, blurb: 'An archway to nowhere, wrapped in moss.' },
  { id: 'abandoned_kiln', name: 'Abandoned Kiln', kind: 'explore', tier: 'low', biome: 'grass', color: 0x7a5a3a, blurb: 'A cold kiln, ash long gone grey.' },
  { id: 'ruined_cottage', name: 'Ruined Cottage', kind: 'explore', tier: 'low', biome: 'grass', color: 0x7a6a4a, blurb: 'Four walls, no roof, no owner.', loot: 'normal_logs' },
  { id: 'buried_doorway', name: 'Buried Doorway', kind: 'lore', tier: 'mid', biome: 'rock', color: 0x6a6a6a, blurb: 'A stone door, sealed and silent.' },
  { id: 'half_sunk_statue', name: 'Half-Sunk Statue', kind: 'explore', tier: 'mid', biome: 'water', color: 0x8a8a7a, blurb: 'A stone goblin sinks into the mire.' },
  { id: 'overgrown_shrine', name: 'Overgrown Shrine', kind: 'shrine', tier: 'low', biome: 'forest', color: 0x5a7a4a, blurb: 'Ivy has claimed this little shrine.' },
  { id: 'derelict_windmill', name: 'Derelict Windmill', kind: 'explore', tier: 'mid', biome: 'grass', color: 0x7a6a4a, blurb: 'Its sails rot where they fell.' },
  { id: 'stone_coffin', name: 'Stone Coffin', kind: 'explore', tier: 'mid', biome: 'grass', color: 0x7a7a7a, blurb: 'Sealed for a reason, surely.', loot: 'coins' },
  { id: 'boundary_stone', name: 'Old Boundary Stone', kind: 'lore', tier: 'low', biome: 'grass', color: 0x8a8a7a, blurb: 'Marks a border no one honours now.' },
  { id: 'charred_homestead', name: 'Charred Homestead', kind: 'explore', tier: 'low', biome: 'grass', color: 0x3a3a3a, blurb: 'Fire took this place, and fast.', loot: 'coins' },
  { id: 'pilgrims_rest', name: "Pilgrim's Rest", kind: 'explore', tier: 'low', biome: 'grass', color: 0x7a6a4a, blurb: 'A bench for travellers who never came.' },
  { id: 'weathered_signpost', name: 'Weathered Signpost', kind: 'lore', tier: 'low', biome: 'any', color: 0x6a5a3a, blurb: 'The arms point every wrong way.' },

  // --- Camps & remains (explore/fight) -------------------------------------
  { id: 'deserted_campfire', name: 'Deserted Campfire', kind: 'explore', tier: 'low', biome: 'any', color: 0x6a4a2a, blurb: 'Embers still warm. Who left in a hurry?' },
  { id: 'poachers_snare', name: "Poacher's Snare", kind: 'explore', tier: 'low', biome: 'forest', color: 0x5a4a3a, blurb: 'A cruel snare, sprung and empty.' },
  { id: 'bandit_leanto', name: 'Bandit Lean-to', kind: 'fight', tier: 'low', biome: 'grass', color: 0x6a5a3a, base: 'bandit', n: 1, blurb: "Someone's watching from the brush." },
  { id: 'smugglers_cache', name: "Smugglers' Cache", kind: 'treasure', tier: 'mid', biome: 'grass', color: 0x5a4a2a, blurb: 'A stash tucked under loose turf.', loot: 'coins' },
  { id: 'abandoned_bedroll', name: 'Abandoned Bedroll', kind: 'explore', tier: 'low', biome: 'any', color: 0x7a6a5a, blurb: 'A bedroll, cold and clammy.' },
  { id: 'cold_cookpot', name: 'Cold Cookpot', kind: 'explore', tier: 'low', biome: 'grass', color: 0x4a4a4a, blurb: 'A pot of something best not tasted.', loot: 'raw_trout' },
  { id: 'broken_wagon', name: 'Broken Wagon', kind: 'explore', tier: 'low', biome: 'grass', color: 0x6a5a3a, blurb: 'A wheel gone, cargo scattered.', loot: 'normal_logs' },
  { id: 'looted_cart', name: 'Looted Cart', kind: 'treasure', tier: 'low', biome: 'grass', color: 0x6a5a3a, blurb: 'Picked clean, but for a coin or two.', loot: 'coins' },
  { id: 'gallows_tree', name: 'Gallows Tree', kind: 'lore', tier: 'mid', biome: 'grass', color: 0x4a3a28, blurb: 'A grim tree with a grimmer history.' },
  { id: 'bone_pile', name: 'Gnawed Bone Pile', kind: 'fight', tier: 'mid', biome: 'grass', color: 0xcfc8b0, base: 'rat', n: 2, blurb: 'Bones, gnawed and worryingly fresh.' },
  { id: 'skull_totem', name: 'Skull Totem', kind: 'lore', tier: 'mid', biome: 'swamp', color: 0x8a7a6a, blurb: 'A warning, in the dialect of skulls.' },
  { id: 'trappers_blind', name: "Trapper's Blind", kind: 'explore', tier: 'low', biome: 'forest', color: 0x4a5a3a, blurb: 'A hunter’s hide, long abandoned.' },
  { id: 'hunters_cache', name: "Hunter's Cache", kind: 'treasure', tier: 'low', biome: 'forest', color: 0x5a4a2a, blurb: 'Furs and a knife, wrapped in hide.', loot: 'coins' },
  { id: 'raider_firepit', name: 'Raider Firepit', kind: 'fight', tier: 'mid', biome: 'grass', color: 0x5a3a2a, base: 'bandit', n: 2, blurb: "The raiders haven't gone far." },
  { id: 'fallen_adventurer', name: 'Fallen Adventurer', kind: 'explore', tier: 'mid', biome: 'any', color: 0x7a6a5a, blurb: 'Poor soul. Their pack remains.', loot: 'bronze_bar' },
  { id: 'torn_tent', name: 'Torn Tent', kind: 'explore', tier: 'low', biome: 'grass', color: 0x7a6a4a, blurb: 'Slashed canvas, flapping in the wind.' },
  { id: 'buried_stash', name: 'Buried Stash', kind: 'treasure', tier: 'low', biome: 'grass', color: 0x6a5a3a, blurb: 'Fresh-turned earth. X marks it.', loot: 'coins' },
  { id: 'old_gibbet', name: 'Old Gibbet', kind: 'lore', tier: 'mid', biome: 'grass', color: 0x4a3a28, blurb: 'A rusted cage that once held a fool.' },

  // --- Natural oddities (oddity) -------------------------------------------
  { id: 'tar_pit', name: 'Bubbling Tar Pit', kind: 'oddity', tier: 'mid', biome: 'swamp', color: 0x2a2a2a, blurb: 'Black tar glugs and pops.' },
  { id: 'hot_geyser', name: 'Hot Geyser', kind: 'oddity', tier: 'mid', biome: 'rock', color: 0x9ad0d0, blurb: 'It spouts scalding water on a whim.' },
  { id: 'crystal_cluster', name: 'Crystal Cluster', kind: 'oddity', tier: 'mid', biome: 'rock', color: 0x9ad0e0, blurb: 'Crystals catch what light there is.', loot: 'coins' },
  { id: 'toadstool_ring', name: 'Glowing Toadstool Ring', kind: 'oddity', tier: 'mid', biome: 'forest', color: 0x6fae7a, blurb: 'Fungi glow faintly. Best not step in.' },
  { id: 'petrified_tree', name: 'Petrified Tree', kind: 'oddity', tier: 'mid', biome: 'grass', color: 0x8a8a7a, blurb: 'A tree turned wholly to stone.' },
  { id: 'struck_oak', name: 'Lightning-Struck Oak', kind: 'oddity', tier: 'low', biome: 'grass', color: 0x3a3a28, blurb: 'Split and blackened by the sky.' },
  { id: 'wild_sinkhole', name: 'Yawning Sinkhole', kind: 'oddity', tier: 'mid', biome: 'grass', color: 0x2a2a2a, blurb: 'The ground simply... stops.' },
  { id: 'sulfur_vent', name: 'Sulfur Vent', kind: 'oddity', tier: 'high', biome: 'rock', color: 0xc0b040, blurb: 'The air stings and reeks of eggs.' },
  { id: 'meteorite_frag', name: 'Meteorite Fragment', kind: 'oddity', tier: 'high', biome: 'grass', color: 0x5ad0d0, blurb: 'A shard of fallen star, still warm.', loot: 'coins' },
  { id: 'salt_flat', name: 'Salt Flat', kind: 'oddity', tier: 'mid', biome: 'sand', color: 0xd0d0c0, blurb: 'A white crust crunches underfoot.' },
  { id: 'quicksand', name: 'Quicksand Patch', kind: 'oddity', tier: 'mid', biome: 'swamp', color: 0x9a8a6a, blurb: 'The ground drinks the unwary.' },
  { id: 'ember_cracks', name: 'Ember Cracks', kind: 'oddity', tier: 'high', biome: 'rock', color: 0xff6a1a, blurb: 'Heat glows in the seams of the rock.' },
  { id: 'fossil_bed', name: 'Fossil Bed', kind: 'oddity', tier: 'mid', biome: 'rock', color: 0x8a8a7a, blurb: 'Old bones, older than goblins.', loot: 'coins' },
  { id: 'amber_seep', name: 'Amber Seep', kind: 'oddity', tier: 'mid', biome: 'forest', color: 0xd0a040, blurb: 'Golden resin, a beetle trapped inside.', loot: 'coins' },
  { id: 'whispering_reeds', name: 'Whispering Reeds', kind: 'oddity', tier: 'low', biome: 'water', color: 0x6fae7a, blurb: 'The reeds murmur when the wind drops.' },
  { id: 'mirror_pool', name: 'Mirror Pool', kind: 'oddity', tier: 'mid', biome: 'water', color: 0x3f77a6, blurb: 'Still water shows more than your face.' },
  { id: 'fairy_circle', name: 'Fairy Circle', kind: 'oddity', tier: 'mid', biome: 'forest', color: 0xc060c0, blurb: 'A perfect ring of pale mushrooms.' },
  { id: 'ancient_root', name: 'Ancient Root', kind: 'oddity', tier: 'high', biome: 'forest', color: 0x5a4530, blurb: 'A root thick as a wall, breathing slow.' },
  { id: 'balancing_boulder', name: 'Balancing Boulder', kind: 'oddity', tier: 'mid', biome: 'rock', color: 0x6a6a6a, blurb: 'A boulder poised on impossibly little.' },
  { id: 'sunbleached_ribs', name: 'Sun-bleached Ribs', kind: 'oddity', tier: 'mid', biome: 'sand', color: 0xcfc8b0, blurb: 'The ribcage of something enormous.' },
  { id: 'glowworm_bank', name: 'Glow-worm Bank', kind: 'oddity', tier: 'mid', biome: 'forest', color: 0xcfe04a, blurb: 'A bank alight with tiny green lamps.' },

  // --- Wildlife & dens (fight/explore) -------------------------------------
  { id: 'rabbit_warren', name: 'Rabbit Warren', kind: 'explore', tier: 'low', biome: 'grass', color: 0xb3a488, blurb: 'Burrows riddle the bank.' },
  { id: 'fox_den', name: 'Fox Den', kind: 'fight', tier: 'low', biome: 'forest', color: 0xb06a3a, base: 'rat', n: 1, blurb: 'Sharp eyes glint from the dark.' },
  { id: 'boar_wallow', name: 'Boar Wallow', kind: 'fight', tier: 'mid', biome: 'forest', color: 0x6a5a3a, base: 'mud_bug', n: 1, blurb: 'Churned mud and a foul temper nearby.' },
  { id: 'wolf_den', name: 'Wolf Den', kind: 'fight', tier: 'mid', biome: 'forest', color: 0x7a7a7a, base: 'bandit', n: 2, blurb: 'Bones at the mouth of a dark den.' },
  { id: 'bat_roost', name: 'Bat Roost', kind: 'fight', tier: 'mid', biome: 'rock', color: 0x4a4a4a, base: 'cave_bug', n: 2, blurb: 'The ceiling shifts and squeaks.' },
  { id: 'spider_nest', name: 'Spider Nest', kind: 'fight', tier: 'mid', biome: 'forest', color: 0x3a3a3a, base: 'cave_bug', n: 2, blurb: 'Webs thick as rope between the trees.' },
  { id: 'snake_pit', name: 'Snake Pit', kind: 'fight', tier: 'mid', biome: 'swamp', color: 0x5a7a3a, base: 'mud_bug', n: 1, blurb: 'A pit that hisses back.' },
  { id: 'wild_beehive', name: 'Wild Beehive', kind: 'gather', tier: 'low', biome: 'forest', color: 0xd0a040, blurb: 'Honey drips. The bees dispute your claim.', loot: 'coins' },
  { id: 'wasp_nest', name: 'Wasp Nest', kind: 'fight', tier: 'low', biome: 'forest', color: 0xc0a040, base: 'rat', n: 2, blurb: 'A grey paper nest, humming with malice.' },
  { id: 'crow_gallows', name: 'Crow Gallows', kind: 'explore', tier: 'mid', biome: 'grass', color: 0x2a2a2a, blurb: "Crows watch from a dead man's tree." },
  { id: 'toad_hollow', name: 'Toad Hollow', kind: 'explore', tier: 'low', biome: 'swamp', color: 0x5a7a4a, blurb: 'Fat toads blink in the muck.' },
  { id: 'badger_sett', name: 'Badger Sett', kind: 'fight', tier: 'low', biome: 'forest', color: 0x7a7a6a, base: 'rat', n: 1, blurb: 'A striped snout, and a bad mood.' },
  { id: 'deer_trail', name: 'Deer Trail', kind: 'explore', tier: 'low', biome: 'forest', color: 0x8a6a4a, blurb: 'Cloven tracks lead deeper in.' },
  { id: 'heron_nest', name: 'Heron Nest', kind: 'explore', tier: 'low', biome: 'water', color: 0x9aaab0, blurb: 'A stilt-legged sentinel of the shallows.' },
  { id: 'frog_pond', name: 'Frog Pond', kind: 'gather', tier: 'low', biome: 'water', color: 0x4f7a3a, blurb: 'A chorus of frogs, and useful reeds.' },
  { id: 'rat_nest', name: 'Rat Nest', kind: 'fight', tier: 'low', biome: 'any', color: 0x7a6a5a, base: 'rat', n: 3, blurb: 'The floor itself seems to move.' },
  { id: 'vulture_perch', name: 'Vulture Perch', kind: 'explore', tier: 'mid', biome: 'rock', color: 0x6a5a4a, blurb: 'They circle where something died.' },
  { id: 'goat_ledge', name: 'Goat Ledge', kind: 'explore', tier: 'mid', biome: 'rock', color: 0x8a8a7a, blurb: 'Sure-footed shapes on the high rocks.' },
  { id: 'owl_hollow', name: 'Owl Hollow', kind: 'explore', tier: 'low', biome: 'forest', color: 0x7a6a5a, blurb: 'Two round eyes, then gone.' },
  { id: 'weasel_burrow', name: 'Weasel Burrow', kind: 'fight', tier: 'low', biome: 'grass', color: 0x9a7a5a, base: 'rat', n: 1, blurb: 'Quick, mean, and toothy.' },

  // --- Roaming / lurking foes (fight) --------------------------------------
  { id: 'lost_scout', name: 'Lost Goblin Scout', kind: 'fight', tier: 'low', biome: 'grass', color: 0x3f6e2c, base: 'bandit', n: 1, blurb: 'One of your own kind, gone feral.' },
  { id: 'feral_hog', name: 'Feral Hog', kind: 'fight', tier: 'low', biome: 'forest', color: 0x6a5a3a, base: 'mud_bug', n: 1, blurb: 'It snorts and paws the earth.' },
  { id: 'mud_lurker', name: 'Mud Lurker', kind: 'fight', tier: 'mid', biome: 'swamp', color: 0x4a5a3a, base: 'mud_bug', n: 1, blurb: 'The mud rises into a shape.' },
  { id: 'rockback_crab', name: 'Rockback Crab', kind: 'fight', tier: 'mid', biome: 'water', color: 0x7a6a5a, base: 'mud_bug', n: 1, blurb: 'A boulder with legs and claws.' },
  { id: 'thornback_boar', name: 'Thornback Boar', kind: 'fight', tier: 'mid', biome: 'forest', color: 0x5a4a3a, base: 'mud_bug', n: 1, blurb: 'Spined and furious.' },
  { id: 'marsh_wight', name: 'Marsh Wight', kind: 'fight', tier: 'high', biome: 'swamp', color: 0x6a7a6a, base: 'bandit', n: 1, blurb: 'A cold light drifts over the fen.' },
  { id: 'hill_bandit', name: 'Hill Bandit', kind: 'fight', tier: 'mid', biome: 'grass', color: 0x6a5a3a, base: 'bandit', n: 2, blurb: 'A blade catches the light on the ridge.' },
  { id: 'cave_straggler', name: 'Cave Straggler', kind: 'fight', tier: 'mid', biome: 'rock', color: 0x4a4a4a, base: 'cave_bug', n: 1, blurb: 'It shuns the sun, and you.' },
  { id: 'bog_leech', name: 'Giant Bog Leech', kind: 'fight', tier: 'mid', biome: 'swamp', color: 0x3a4a2a, base: 'mud_bug', n: 1, blurb: 'It smells your warmth.' },
  { id: 'wild_goblin', name: 'Wild Goblin', kind: 'fight', tier: 'low', biome: 'grass', color: 0x4f7a3a, base: 'bandit', n: 1, blurb: 'No tribe, no manners.' },
  { id: 'starving_wolf', name: 'Starving Wolf', kind: 'fight', tier: 'mid', biome: 'forest', color: 0x8a8a7a, base: 'bandit', n: 1, blurb: 'Ribs showing, eyes bright.' },
  { id: 'ridge_vulture', name: 'Ridge Vulture', kind: 'fight', tier: 'mid', biome: 'rock', color: 0x6a5a4a, base: 'rat', n: 2, blurb: "It's decided you look edible." },
  { id: 'ash_imp', name: 'Ash Imp', kind: 'fight', tier: 'high', biome: 'rock', color: 0xff6a1a, base: 'cave_bug', n: 1, blurb: 'A spiteful cinder with teeth.' },
  { id: 'golem_shard', name: 'Stone Golem Shard', kind: 'fight', tier: 'high', biome: 'rock', color: 0x6a6a6a, base: 'cave_bug', n: 1, blurb: 'A chunk of a bigger, worse thing.' },
  { id: 'bramble_beast', name: 'Bramble Beast', kind: 'fight', tier: 'mid', biome: 'forest', color: 0x3f6e2c, base: 'mud_bug', n: 1, blurb: 'The thicket stands up and turns.' },
  { id: 'fen_stalker', name: 'Fen Stalker', kind: 'fight', tier: 'high', biome: 'swamp', color: 0x4a5a3a, base: 'bandit', n: 1, blurb: 'Ripples, then silence, then teeth.' },
  { id: 'dust_devil', name: 'Dust Devil', kind: 'fight', tier: 'mid', biome: 'sand', color: 0xa89a78, base: 'cave_bug', n: 1, blurb: 'A whirl of grit with ill intent.' },
  { id: 'root_horror', name: 'Root Horror', kind: 'fight', tier: 'high', biome: 'forest', color: 0x5a4530, base: 'bandit', n: 1, blurb: 'The ground grips your ankle.' },
  { id: 'grave_crawler', name: 'Grave Crawler', kind: 'fight', tier: 'mid', biome: 'grass', color: 0x7a7a7a, base: 'cave_bug', n: 2, blurb: 'Something claws up from below.' },
  { id: 'frost_moth', name: 'Frost Moth Swarm', kind: 'fight', tier: 'high', biome: 'rock', color: 0xc0c0e0, base: 'cave_bug', n: 2, blurb: 'Pale wings, and a numbing chill.' },

  // --- Foraging micro-nodes (gather) ---------------------------------------
  { id: 'berry_bush', name: 'Berry Bush', kind: 'gather', tier: 'low', biome: 'forest', color: 0xc44a6a, blurb: 'Plump berries, if the birds left any.', loot: 'coins' },
  { id: 'herb_patch', name: 'Wild Herb Patch', kind: 'gather', tier: 'low', biome: 'grass', color: 0x5a7a3a, blurb: 'Fragrant leaves worth picking.' },
  { id: 'mushroom_cluster', name: 'Wild Mushroom Cluster', kind: 'gather', tier: 'low', biome: 'forest', color: 0xd08040, blurb: 'A cluster of edible-looking caps.' },
  { id: 'birds_nest', name: "Bird's Nest", kind: 'gather', tier: 'low', biome: 'forest', color: 0x7a6a4a, blurb: 'Eggs, and maybe a dropped ring.', loot: 'coins' },
  { id: 'clay_pit', name: 'Clay Pit', kind: 'gather', tier: 'low', biome: 'water', color: 0x8a6a4a, blurb: 'Good grey clay for the taking.' },
  { id: 'reed_bed', name: 'Reed Bed', kind: 'gather', tier: 'low', biome: 'water', color: 0x6fae7a, blurb: 'Tall reeds, useful for many things.' },
  { id: 'flint_outcrop', name: 'Flint Outcrop', kind: 'gather', tier: 'low', biome: 'rock', color: 0x6a6a6a, blurb: 'Sharp flint splits from the stone.' },
  { id: 'chalk_vein', name: 'Chalk Vein', kind: 'gather', tier: 'mid', biome: 'rock', color: 0xd0d0c0, blurb: 'A white seam threads the rock.' },
  { id: 'wild_onion', name: 'Wild Onion Patch', kind: 'gather', tier: 'low', biome: 'grass', color: 0x8a9a5a, blurb: 'Pungent bulbs beneath the leaves.' },
  { id: 'nettle_thicket', name: 'Nettle Thicket', kind: 'gather', tier: 'low', biome: 'forest', color: 0x3f6e2c, blurb: 'Stings, but the leaves are prized.' },
  { id: 'cattail_stand', name: 'Cattail Stand', kind: 'gather', tier: 'low', biome: 'water', color: 0x5f7d3c, blurb: 'Brown spikes bob at the water’s edge.' },
  { id: 'mossy_log', name: 'Mossy Log', kind: 'gather', tier: 'low', biome: 'forest', color: 0x5a6a4a, blurb: 'Damp wood, and something living under it.' },
  { id: 'fallen_branches', name: 'Fallen Branches', kind: 'gather', tier: 'low', biome: 'forest', color: 0x6a5a3a, blurb: 'Dry kindling, free for the gathering.', loot: 'normal_logs' },
  { id: 'wildflower_meadow', name: 'Wildflower Meadow', kind: 'gather', tier: 'low', biome: 'grass', color: 0xf0d85a, blurb: 'A haze of colour and bees.' },
  { id: 'honey_tree', name: 'Honey Tree', kind: 'gather', tier: 'mid', biome: 'forest', color: 0xd0a040, blurb: 'A hollow trunk heavy with comb.', loot: 'coins' },

  // --- Lore & mystery (lore/treasure) --------------------------------------
  { id: 'scratched_runestone', name: 'Scratched Runestone', kind: 'lore', tier: 'mid', biome: 'rock', color: 0x9a9aa0, blurb: 'The scratches almost form words.' },
  { id: 'buried_journal', name: 'Buried Journal', kind: 'lore', tier: 'mid', biome: 'grass', color: 0x7a6a5a, blurb: 'Rain-warped pages, a last entry.', loot: 'coins' },
  { id: 'dead_mans_cache', name: "Dead Man's Cache", kind: 'treasure', tier: 'mid', biome: 'grass', color: 0x6a5a3a, blurb: 'He hid it well. Not well enough.', loot: 'coins' },
  { id: 'cryptic_cairn', name: 'Cryptic Cairn', kind: 'lore', tier: 'mid', biome: 'rock', color: 0x8a8a7a, blurb: 'Stacked stones marking... what?' },
  { id: 'cave_mark', name: 'Painted Cave-mark', kind: 'lore', tier: 'low', biome: 'rock', color: 0xb03030, blurb: 'A red hand, pressed long ago.' },
  { id: 'message_bottle', name: 'Message in a Bottle', kind: 'lore', tier: 'low', biome: 'water', color: 0x3f77a6, blurb: 'A plea, or a joke, sealed in glass.' },
  { id: 'old_battlefield', name: 'Old Battlefield', kind: 'lore', tier: 'mid', biome: 'grass', color: 0x6a5a4a, blurb: 'Rusted iron, and worse, in the grass.', loot: 'bronze_bar' },
  { id: 'mass_grave', name: 'Mass Grave', kind: 'lore', tier: 'high', biome: 'grass', color: 0x4a3a28, blurb: 'A mound that should be left alone.' },
  { id: 'hermits_marker', name: "Hermit's Marker", kind: 'lore', tier: 'low', biome: 'forest', color: 0x7a6a4a, blurb: 'Someone chose to be forgotten here.' },
  { id: 'ancient_milestone', name: 'Ancient Milestone', kind: 'lore', tier: 'mid', biome: 'any', color: 0x8a8a7a, blurb: 'A distance, to a place unnamed.' },
  { id: 'faded_mural', name: 'Faded Mural', kind: 'lore', tier: 'mid', biome: 'rock', color: 0x8a7a6a, blurb: 'Goblins, painted mid-triumph.' },
  { id: 'warning_totem', name: 'Warning Totem', kind: 'lore', tier: 'mid', biome: 'swamp', color: 0x8a7a6a, blurb: 'Turn back, it says, without words.' },
  { id: 'lost_locket', name: 'Lost Locket', kind: 'treasure', tier: 'low', biome: 'grass', color: 0xd0c040, blurb: 'Someone will miss this. Finders keepers.', loot: 'coins' },
  { id: 'tattered_banner', name: 'Tattered Banner', kind: 'lore', tier: 'mid', biome: 'grass', color: 0xb03030, blurb: 'A sigil no living goblin flies.' },
  { id: 'bloodstained_altar', name: 'Bloodstained Altar', kind: 'lore', tier: 'high', biome: 'rock', color: 0x7a3030, blurb: 'The stains are old. Mostly.' },

  // --- Treasure & reward (treasure) ----------------------------------------
  { id: 'buried_chest', name: 'Buried Chest', kind: 'treasure', tier: 'mid', biome: 'grass', color: 0x8a6a3a, blurb: 'A corner of iron, poking from the soil.', loot: 'coins' },
  { id: 'loose_flagstone', name: 'Loose Flagstone', kind: 'treasure', tier: 'low', biome: 'grass', color: 0x8a8a7a, blurb: 'It wobbles. Something’s underneath.', loot: 'coins' },
  { id: 'hollow_log_stash', name: 'Hollow Log Stash', kind: 'treasure', tier: 'low', biome: 'forest', color: 0x5a4530, blurb: 'A cache tucked in a rotten log.', loot: 'coins' },
  { id: 'coin_purse', name: 'Dropped Coin Purse', kind: 'treasure', tier: 'low', biome: 'any', color: 0xd0c040, blurb: 'Someone’s loss, your gain.', loot: 'coins' },
  { id: 'dropped_pack', name: 'Dropped Pack', kind: 'treasure', tier: 'low', biome: 'any', color: 0x6a5a3a, blurb: 'Abandoned in a hurry, still full.', loot: 'normal_logs' },
  { id: 'glittering_crevice', name: 'Glittering Crevice', kind: 'treasure', tier: 'mid', biome: 'rock', color: 0x9ad0e0, blurb: 'Something bright wedged in the crack.', loot: 'coins' },
  { id: 'sunken_strongbox', name: 'Sunken Strongbox', kind: 'treasure', tier: 'mid', biome: 'water', color: 0x6a5a3a, blurb: 'It sits just under the surface.', loot: 'coins' },
  { id: 'rootbound_chest', name: 'Root-bound Chest', kind: 'treasure', tier: 'mid', biome: 'forest', color: 0x5a4530, blurb: 'Roots have grown right through it.', loot: 'coins' },
  { id: 'cairn_cache', name: 'Cairn Cache', kind: 'treasure', tier: 'mid', biome: 'rock', color: 0x8a8a7a, blurb: 'A hollow beneath the topmost stone.', loot: 'coins' },
  { id: 'prospectors_stash', name: "Prospector's Stash", kind: 'treasure', tier: 'mid', biome: 'rock', color: 0x7a6a4a, blurb: 'Ore they never came back for.', loot: 'iron_ore' },
  { id: 'old_coffer', name: 'Old Coffer', kind: 'treasure', tier: 'mid', biome: 'grass', color: 0x8a6a3a, blurb: 'The lock gave up years ago.', loot: 'coins' },
  { id: 'beggars_hoard', name: "Beggar's Hoard", kind: 'treasure', tier: 'low', biome: 'grass', color: 0x6a5a3a, blurb: 'A surprising fortune in small coins.', loot: 'coins' },

  // --- Shrines & boons (shrine) --------------------------------------------
  { id: 'wishing_well', name: 'Wishing Well', kind: 'shrine', tier: 'low', biome: 'grass', color: 0x6a6a6a, blurb: 'Toss a coin, or take a few.', loot: 'coins' },
  { id: 'prayer_stone', name: 'Prayer Stone', kind: 'shrine', tier: 'low', biome: 'grass', color: 0x8a8a7a, blurb: 'Smooth from a thousand foreheads.' },
  { id: 'offering_bowl', name: 'Offering Bowl', kind: 'shrine', tier: 'mid', biome: 'forest', color: 0x8a7a5a, blurb: 'Someone left fruit. It’s gone now.' },
  { id: 'spirit_totem', name: 'Spirit Totem', kind: 'shrine', tier: 'mid', biome: 'swamp', color: 0x8a7a6a, blurb: 'The paint moves when you don’t look.' },
  { id: 'blessed_spring', name: 'Blessed Spring', kind: 'shrine', tier: 'mid', biome: 'water', color: 0x9ad0d0, blurb: 'The water is impossibly clear.' },
  { id: 'cursed_idol', name: 'Cursed Idol', kind: 'shrine', tier: 'high', biome: 'grass', color: 0x7a3030, blurb: 'It watches. Definitely, it watches.' },
  { id: 'moss_shrine', name: 'Moss Shrine', kind: 'shrine', tier: 'low', biome: 'forest', color: 0x5a7a4a, blurb: 'A tiny god, green and patient.' },
  { id: 'ancestor_post', name: 'Ancestor Post', kind: 'shrine', tier: 'mid', biome: 'grass', color: 0x7a6a4a, blurb: 'Carved faces of goblins long dead.' },
  { id: 'luck_stone', name: 'Luck Stone', kind: 'shrine', tier: 'mid', biome: 'rock', color: 0x9ad0e0, blurb: 'Rub it. It can’t hurt. Probably.', loot: 'coins' },
];
